"""add system configs and dept bonus start date

Revision ID: 3123f97a8e6e
Revises: fb73f3a5a842
Create Date: 2026-01-29 17:30:47.462273

"""
from alembic import op
import sqlalchemy as sa


# 修订标识符，由 Alembic 使用
revision = '3123f97a8e6e'
down_revision = 'fb73f3a5a842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置ID，主键'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键（唯一）'),
    sa.Column('value', sa.String(length=500), nullable=True, comment='配置值（字符串格式）'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='配置说明'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_start_date', sa.Date(), nullable=True, comment='自动加分计算的基准起始日期（为空时使用系统默认配置）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('bonus_start_date')

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))

    op.drop_table('system_configs')
    # ### end Alembic commands ###
