"""add admin_users table and admin_departments association table

Revision ID: fb73f3a5a842
Revises: 20260126_add_certificate_types
Create Date: 2026-01-26 17:30:55.681027

"""
from alembic import op
import sqlalchemy as sa


# 修订标识符，由 Alembic 使用
revision = 'fb73f3a5a842'
down_revision = '20260126_add_certificate_types'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='管理员ID，主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号（唯一）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：super(超级管理员) 或 normal(普通管理员)'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('admin_departments',
    sa.Column('admin_id', sa.Integer(), nullable=False, comment='管理员ID'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='部门ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='关联创建时间'),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('admin_id', 'department_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_departments')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.drop_index(batch_op.f('ix_admin_users_role'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
